export const UPDATE_COUNT = "@STATE/UPDATE_COUNT"

export const UPDATE_ALGORITHMS = "@STATE/UPDATE_ALGORITHMS"
export const UPDATE_TARGET_ATTRIBUTES = "@STATE/UPDATE_TARGET_ATTRIBUTES"
export const UPDATE_EXPERIMENT_LIST = "@STATE/UPDATE_EXPERIMENT_LIST"

// Model result API constants
export const UPDATE_METRICS = "@STATE/UPDATE_METRICS"
export const UPDATE_INFO = "@STATE/UPDATE_INFO"
export const UPDATE_TAGS = "@STATE/UPDATE_TAGS"
export const UPDATE_PARAMS = "@STATE/UPDATE_PARAMS"