export const URLPathConstants = {
    FETCH_ALGORITHMS: "mlflow/algorithms",
    UPLOAD_CSV_CLASSIFICATION: "classification/csv-upload",
    TRAIN_MODEL_CLASSIFICATION: "classification/train-model",
    PREDICTION_CLASSIFICATION: "classification/predict",
    RETRAIN_MODEL_CLASSIFICATION: "classification/re-train-model",
    FETCH_EXPERIMENT_RUNS: "mlflow/experiment/runs",
    FETCH_EXPERIMENT_LIST: "mlflow/experiment-list",
    FETCH_DEPLOYED_MODELS: "mlflow/deployed-models",
    DEPLOY_MODEL: "mlflow/deploy-model",
    FETCH_RUN_BY_ID: "mlflow/run",
    FETCH_EXPERIMENT_BY_ID: "mlflow/experiment",
    CLASSIFICATION: "classification",
    MLFLOW: "mlflow",
}
