version: "3"

services:
  
  core:
    build: 
      context: ./Backend/src/core
      dockerfile: core.dockerfile
    ports:
        - "${PORTMLFLOW}:${PORTMLFLOW}"

  classification:
    build: 
      context: ./Backend/src/pipelines/classification
      dockerfile: classification.dockerfile
    ports:
        - "${PORTCLASSIFICATION}:${PORTCLASSIFICATION}"
    