version: "3.9"

services:

  core:
    # image: python:3.9-alpine
    build:
      context: ./Backend/src
      dockerfile: "core/core.dockerfile"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "${PORT_MLFLOW}:${PORT_MLFLOW}"
    volumes:
      - mymlruns:${SHARED_VOLUME}
    networks:
      - mlapp-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${PORT_MLFLOW} || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  classification:
    # image: python:3.9-alpine
    build:
      context: ./Backend/src
      dockerfile: "pipelines/classification/classification.dockerfile"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "${PORT_CLASSIFICATION}:${PORT_CLASSIFICATION}"
    volumes:
      - mymlruns:${SHARED_VOLUME}
    depends_on:
      - core
    networks:
      - mlapp-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${PORT_CLASSIFICATION} || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mlapp-net:
    driver: bridge

volumes:
  mymlruns:
